services:
    smart_db_dumper.manager:
        class: SmartCore\Bundle\DbDumperBundle\Manager\DatabaseManager
        public: true
        arguments: [ "@doctrine.orm.entity_manager", "%smart_db_dumper.backups_dir%", "%smart_db_dumper.timeout%", "%smart_db_dumper.filename%" ]
        calls:
            - [ setContainer, [ "@service_container" ] ]
            - [ init ]

    smart_db_dumper.dump_command:
        class: SmartCore\Bundle\DbDumperBundle\Command\DumpCommand
        tags:
            - { name: console.command }
            - { command: 'smart:dbdumper:dump' }

    smart_db_dumper.restore_command:
        class: SmartCore\Bundle\DbDumperBundle\Command\RestoreCommand
        tags:
            - { name: console.command }
            - { command: 'smart:dbdumper:restore' }
